version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-java
    ports:
      - "5673:5672" 
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  mongodb:

    image: mongo:6.0
    container_name: mongodb-java
    ports:
      - "27018:27017" 
    volumes:
      - mongodb_data:/data/db

  mailhog:
     image: mailhog/mailhog
     container_name: mailhog-java
     ports:
        - "1026:1025" 
        - "8026:8025" 

volumes:
  mongodb_data: