spring.application.name=ProjetoChatGPT04_Java

#tomcat
server.port=8083

#mongodb
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27018
spring.data.mongodb.database=bdclientes

#openai
openai.api.url=https://api.openai.com/v1/chat/completions
openai.api.key=your key here

#rabbitmq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5673
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.virtual-host=/