spring.application.name=ProjetoChatGPT04_Java

#tomcat
server.port=8083

#mongodb
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27018
spring.data.mongodb.database=bdclientes

#openai
openai.api.url=https://api.openai.com/v1/chat/completions
openai.api.key=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